### PR TITLE
Ft department view checks #158174596

### PR DESCRIPTION
**Pull request by matthewacha**
## Status
**READY**

## Migrations
YES

## Description
Different departments within a team should be able to categorise jobs within their domains to a separate view. I have integrated filtering of jobs by departments

## Related PRs
None

## Todos
- [x] Tests
- [x] views
- [x] checks UI

## Deploy Notes
On deployment run migrations ```./manage.py migrate```

Run background processes  ```./manage.py ensuretriggers``` and ```./manage.py sendalerts```

## Steps to Test or Reproduce

```sh
To assign department to check:
- navigate to the name of a check
- On the displayed form add a department(s)
- save the entry

to view checks by department:
- navigate to each department link displayed below 
  My Checks 
```

## Impacted Areas in Application

* /checks/ page
* checks model
* my_ckecks method in hc/front/views.py

## Snapshots 
image

image

### CODE REVIEW

**Comment by EdwinKato** [comment]
@matthewacha since you have `To dos` that are not checked, the status can't be ready.

**Comment by EdwinKato** [comment]
@Jpkat92 , @archbishop12 review this PR and either approve or request changes. I will only start my full review after your reviews

**Review by JaymesKat — DISMISSED** [review]

**Comment by EdwinKato** [comment]
@matthewacha under `Steps to Test or Reproduce`, add steps on how someone can add and view checks by department. Moving forward, always add the steps someone should go through to see the expected outcome under that section. I have a good example if this is not clear enough

**Review by EdwinKato — APPROVED** [review]
Nice work!

**Pull request merged**
